### ISSUE TITLE
Several intervals based on the same hardware timer - how to use?

### ISSUE THREAD

**Issue by vorlovsky** [khoih-prog/TimerInterrupt#4]
Hi!

It's not clear how the one can instantiate and use several timers based on a single hardware timer. I've checked the given examples and searched over the internet, but it's the same info available everywhere. All the examples seems to represent the same approach: init  e.g. ITimer1, then attachInterruptInterval to it, in case the second timer is needed - ITimer2 goes through the same process, and that's all. As I understand, these two instances use different HW timers and so I have no idea how up to 16(!) timers can be attached/detached this way.

Please, help.

BR, Vyacheslav

**Comment by khoih-prog** [comment]
@vorlovsky 

Thanks for using the library.

Please have a look at [**New from v102**](https://github.com/khoih-prog/TimerInterrupt#new-from-v102) and example [**ISR_Timer_Complex**](https://github.com/khoih-prog/TimerInterrupt/tree/master/examples/ISR_Timer_Complex).

The [**ISR_Timer_Complex**](https://github.com/khoih-prog/TimerInterrupt/tree/master/examples/ISR_Timer_Complex) example demontrates the usage of **4 ISR-timers using just ITimer1.**

You can use max 16 timers for each HW ITimer.
